### ISSUE TITLE
practica 6 unidad 3 hilos consola c#

### ISSUE THREAD

**Issue by ang3-l32** [SistemasTecTlaxiaco/practica-de-hilos-ang3-l32#2]
[practica 6  unidad 3 hilos consola c# topicos.pdf](https://github.com/SistemasTecTlaxiaco/practica-de-hilos-ang3-l32/files/8590582/practica.6.unidad.3.hilos.consola.c.topicos.pdf)

**Comment by josealfredo79** [comment]
Bien hecho y revisado...

**Comment by josealfredo79** [comment]
Falta la calificación...
