### ISSUE TITLE
practica 6consola

### ISSUE THREAD

**Issue by ang3-l32** [SistemasTecTlaxiaco/practica-de-hilos-ang3-l32#4]
[practica 6  unidad 3 hilos consola c# topicos.pdf](https://github.com/SistemasTecTlaxiaco/practica-de-hilos-ang3-l32/files/8590638/practica.6.unidad.3.hilos.consola.c.topicos.pdf)

**Comment by ang3-l32** [comment]
[practica 6  unidad 3 hilos consola c# topicos.pdf](https://github.com/SistemasTecTlaxiaco/practica-de-hilos-ang3-l32/files/8590641/practica.6.unidad.3.hilos.consola.c.topicos.pdf)

**Comment by Yareli-Perez** [comment]
calificación = 55  = 11%

falta tabla de ilustraciones, mas ilustraciones tienes 7 de 20 ilustraciones y falto la conclusión
