### ISSUE TITLE
practica 6 multi hilos unidad 3

### ISSUE THREAD

**Issue by ang3-l32** [SistemasTecTlaxiaco/practica-de-hilos-ang3-l32#6]
[practica 6 multihilos  unidad 3topicos.pdf](https://github.com/SistemasTecTlaxiaco/practica-de-hilos-ang3-l32/files/8853504/practica.6.multihilos.unidad.3topicos.pdf)

**Comment by abicoronel** [comment]
Calificación: 15

**Comment by josealfredo79** [comment]
Se debe describir la practica correctamente
![image](https://user-images.githubusercontent.com/58342642/172403227-939e5cd2-0af0-4bb3-93d3-3c9bd1e07665.png)
