### ISSUE TITLE
multitarea practica 6

### ISSUE THREAD

**Issue by ang3-l32** [SistemasTecTlaxiaco/practica-de-hilos-ang3-l32#7]
[multitarea practica 6 unidad 3topicos.pdf](https://github.com/SistemasTecTlaxiaco/practica-de-hilos-ang3-l32/files/8884952/multitarea.practica.6.unidad.3topicos.pdf)

**Comment by abicoronel** [comment]
Calificación: 18%

**Comment by josealfredo79** [comment]
Bien hecho y revisado
